/api/profiles:
  get:
    tags:
      - Profiles
    description: Get all profiles
    operationId: GetProfiles
    parameters:
      - in: query
        name: pagination
        schema:
          type: boolean
          default: "true"
        description: active pagination
      - in: query
        name: limit
        schema:
          type: integer
          default: 10
        description: amount per page
      - in: query
        name: offset
        schema:
          type: integer
          default: 1
        description: number page
      - in: query
        name: name
        schema:
          type: string
        description: filter for name
      - in: query
        name: active
        schema:
          type: boolean
        description: filter for state
    responses:
      200:
        description: OK
        content:
            application/json:
              schema:
                type: array
                items:
                  allOf:
                    - $ref: "#/components/schemas/Profiles"
                    - $ref: "#/components/schemas/Pagination" 
      400:
        description: Bad Request
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Error"
      401:
        description: Unauthenticated
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Error"
      404:
        description: Not Found
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Error"
      405:
        description: Not Allowed
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Error"
      500:
        description: Internal Server Error
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Error"

    x-codegen-request-body-name: body
  post:
    tags:
      - Profiles
    description: Create a new Profile
    operationId: PostProfile
    requestBody:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/CreateProfile"
      required: true
    responses:
      201:
        description: CREATED
        content:
            application/json:
              schema:
                $ref: "#/components/schemas/Profile" 
      400:
        description: Bad Request
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Error"
      401:
        description: Unauthenticated
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Error"
      404:
        description: Not Found
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Error"
      405:
        description: Not Allowed
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Error"
      500:
        description: Internal Server Error
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Error"

    x-codegen-request-body-name: body
/api/profiles/{id}:
  get:
    tags:
      - Profiles
    description: Get one Profile
    operationId: Get Profile
    parameters:
      - in: path
        name: id
        schema:
          type: integer
          format: int32
        description: Id Profile
        required: true
    responses:
      200:
        description: OK
        content:
            application/json:
              schema:
                $ref: "#/components/schemas/Profile" 
      400:
        description: Bad Request
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Error"
      401:
        description: Unauthenticated
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Error"
      404:
        description: Not Found
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Error"
      405:
        description: Not Allowed
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Error"
      500:
        description: Internal Server Error
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Error"

    x-codegen-request-body-name: body
  put:
    tags:
      - Profiles
    description: Update Profile
    operationId: updateProfile
    parameters:
      - in: path
        name: id
        schema:
          type: integer
          format: int32
        description: Id Profile
        required: true
    requestBody:
      content:
        application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/CreateProfile"
                  - type: object
                    properties:
                      isActive:
                        type: boolean
      required: true
    responses:
      200:
        description: OK
        content:
            application/json:
              schema:
                $ref: "#/components/schemas/Profile" 
      400:
        description: Bad Request
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Error"
      401:
        description: Unauthenticated
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Error"
      404:
        description: Not Found
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Error"
      405:
        description: Not Allowed
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Error"
      500:
        description: Internal Server Error
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Error"

    x-codegen-request-body-name: body
  delete:
    tags:
      - Profiles
    description: Delete Profile
    operationId: deleteProfile
    parameters:
      - in: path
        name: id
        schema:
          type: integer
          format: int32
        description: Id Profile
        required: true
    responses:
      200:
        description: Profile deleted successfully
        content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                description: Profile deleted successfully
      400:
        description: Bad Request
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Error"
      401:
        description: Unauthenticated
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Error"
      404:
        description: Not Found
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Error"
      405:
        description: Not Allowed
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Error"
      500:
        description: Internal Server Error
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Error"

    x-codegen-request-body-name: body